### ISSUE TITLE
Issue with iasl compiler

### ISSUE THREAD

**Issue by rhaix** [m4ng0squ4sh/razer_blade_14_2016_acpi_fix#2]
I was getting "No such file or directory" error 6092, for some reason, with the latest iasl package installed in ubuntu 16.04.01.

I was able to fix this by adding the -p <$TEMPDIR/SSDT5> to the script like this:

`iasl -ve -tc -p "$TMPDIR/SSDT5" "$TMPDIR/SSDT5.dsl" `

Just leaving this here in case someone finds the same problem.

**Comment by r0l1** [comment]
Thanks! What's your exact iasl version?

**Comment by lungten** [comment]
I am trying to compile this fix for RAZER BLADE 2016 (1060) and I get the following warning. Is it something to worry about?
`iASL Warning: There were 16 external control methods found during
 disassembly, but only 14 were resolved (2 unresolved). Additional
 ACPI tables may be required to properly disassemble the code. This
 resulting disassembler output file may not compile because the
 disassembler did not know how many arguments to assign to the
 unresolved methods. Note: SSDTs can be dynamically loaded at
 runtime and may or may not be available via the host OS.`
