### ISSUE TITLE
Compiler Warning

### ISSUE THREAD

**Issue by ghost** [m4ng0squ4sh/razer_blade_14_2016_acpi_fix#3]
I am trying to compile this fix for RAZER BLADE 2016 (1060) and I get the following warning. Is it something to worry about?
`iASL Warning: There were 16 external control methods found during
 disassembly, but only 14 were resolved (2 unresolved). Additional
 ACPI tables may be required to properly disassemble the code. This
 resulting disassembler output file may not compile because the
 disassembler did not know how many arguments to assign to the
 unresolved methods. Note: SSDTs can be dynamically loaded at
 runtime and may or may not be available via the host OS.`

**Comment by r0l1** [comment]
As long as it compiles successfully, this isn't a problem.
If you attach your [ACPI tables](https://github.com/m4ng0squ4sh/razer_blade_14_2016_acpi_fix/blob/master/scripts/get_acpi_tables.sh), I could have a look at it and check if this fix works for your model.

**Comment by lungten** [comment]
[acpi_tables.tar.gz](https://github.com/m4ng0squ4sh/razer_blade_14_2016_acpi_fix/files/676548/acpi_tables.tar.gz)
@m4ng0squ4sh The compilation seems to succeed but since I am running Ubuntu 16.10 (meaning GRUB2) I am not able to load multiple initrd images as you have done for your Arch setup.

If it would help, my system is the one with new GTX 1060 card.

I have followed 
https://github.com/Bumblebee-Project/Bumblebee/issues/764
but does not seem to have a working solution so far.
